using System.Xml;
using STIGForge.Core.Models;

namespace STIGForge.Content.Import;

/// <summary>
/// Parses domain-level GPO backup folders found in the root GPOs/ directory of a
/// DISA STIG GPO package. These backups are intended for GPMC import on domain
/// controllers only — admins apply them manually via Import-GPO.
///
/// GPO backup folder structure:
///   GPOs/{GUID}/Backup.xml         ← GPO metadata (display name, GUID, creation time)
///   GPOs/{GUID}/gpreport.xml       ← full GPO settings report
///   GPOs/{GUID}/bkupInfo.xml       ← backup metadata
///   GPOs/{GUID}/DomainSysvol/GPO/  ← policy artifacts (Registry.pol, GptTmpl.inf, etc.)
/// </summary>
public static class DomainGpoBackupParser
{
    /// <summary>
    /// Discovers all GPO backup folders under the extracted root's GPOs/ directory
    /// and parses their metadata into control records tagged as DC-only / manual.
    /// </summary>
    public static DomainGpoParseResult ParseBackups(string extractedRoot, string packName)
    {
        var controls = new List<ControlRecord>();
        var backups = new List<DomainGpoBackupInfo>();
        var warnings = new List<string>();

        var gposRoot = FindGposRoot(extractedRoot);
        if (gposRoot == null)
            return new DomainGpoParseResult { Controls = controls, Backups = backups, Warnings = warnings };

        foreach (var backupDir in Directory.EnumerateDirectories(gposRoot))
        {
            var dirName = Path.GetFileName(backupDir);

            // GPO backup folders are typically GUID-named
            if (!IsGuidLike(dirName))
                continue;

            try
            {
                var info = ParseBackupFolder(backupDir, dirName);
                if (info != null)
                {
                    backups.Add(info);
                    controls.Add(CreateControlRecord(info, packName));
                }
            }
            catch (Exception ex)
            {
                warnings.Add($"Domain GPO backup parse failed ({dirName}): {ex.Message}");
            }
        }

        return new DomainGpoParseResult
        {
            Controls = controls,
            Backups = backups,
            Warnings = warnings
        };
    }

    /// <summary>
    /// Generates a PowerShell script that admins can run on a domain controller
    /// to import all staged domain GPO backups into GPMC.
    /// </summary>
    public static string GenerateGpmcImportScript(IReadOnlyList<DomainGpoBackupInfo> backups, string stagedGposPath)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("#Requires -Modules GroupPolicy");
        sb.AppendLine("# Import-DomainGpos.ps1");
        sb.AppendLine("# Generated by STIGForge — run on a Domain Controller with GPMC installed.");
        sb.AppendLine("# This script imports DISA STIG domain GPO backups into Active Directory.");
        sb.AppendLine("# Review each GPO before linking to OUs.");
        sb.AppendLine();
        sb.AppendLine("param(");
        sb.AppendLine("    [string]$BackupPath = $PSScriptRoot,");
        sb.AppendLine("    [switch]$WhatIf");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();

        foreach (var backup in backups)
        {
            var safeName = backup.DisplayName.Replace("'", "''");
            sb.AppendLine($"# GPO: {backup.DisplayName}");
            sb.AppendLine($"Write-Host \"Importing GPO: {safeName}\" -ForegroundColor Cyan");
            sb.AppendLine("if (-not $WhatIf) {");
            sb.AppendLine($"    Import-GPO -BackupId '{backup.BackupId}' -Path $BackupPath -TargetName '{safeName}' -CreateIfNeeded");
            sb.AppendLine("} else {");
            sb.AppendLine($"    Write-Host \"  [WhatIf] Would import backup {backup.BackupId} as '{safeName}'\" -ForegroundColor Yellow");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("Write-Host \"Domain GPO import complete. Review and link GPOs to appropriate OUs.\" -ForegroundColor Green");
        return sb.ToString();
    }

    private static DomainGpoBackupInfo? ParseBackupFolder(string backupDir, string dirGuid)
    {
        // Try Backup.xml first (standard GPO backup metadata)
        var backupXml = Path.Combine(backupDir, "Backup.xml");
        if (File.Exists(backupXml))
            return ParseBackupXml(backupXml, backupDir, dirGuid);

        // Try bkupInfo.xml as fallback
        var bkupInfoXml = Path.Combine(backupDir, "bkupInfo.xml");
        if (File.Exists(bkupInfoXml))
            return ParseBkupInfoXml(bkupInfoXml, backupDir, dirGuid);

        // No metadata found but has DomainSysvol — treat as unnamed backup
        var domainSysvol = Path.Combine(backupDir, "DomainSysvol");
        if (Directory.Exists(domainSysvol))
        {
            return new DomainGpoBackupInfo
            {
                BackupId = dirGuid,
                DisplayName = $"GPO Backup {dirGuid}",
                BackupPath = backupDir
            };
        }

        return null;
    }

    private static DomainGpoBackupInfo ParseBackupXml(string xmlPath, string backupDir, string dirGuid)
    {
        var settings = new XmlReaderSettings
        {
            DtdProcessing = DtdProcessing.Prohibit,
            XmlResolver = null,
            IgnoreWhitespace = true
        };

        string? displayName = null;
        string? gpoGuid = null;
        string? backupId = null;

        using var reader = XmlReader.Create(xmlPath, settings);
        while (reader.Read())
        {
            if (reader.NodeType != XmlNodeType.Element)
                continue;

            switch (reader.LocalName)
            {
                case "DisplayName":
                    displayName = reader.ReadElementContentAsString()?.Trim();
                    break;
                case "GroupPolicyObjectId" or "ID":
                    gpoGuid ??= reader.ReadElementContentAsString()?.Trim();
                    break;
                case "BackupId":
                    backupId = reader.ReadElementContentAsString()?.Trim();
                    break;
            }
        }

        return new DomainGpoBackupInfo
        {
            BackupId = backupId ?? dirGuid,
            GpoGuid = gpoGuid,
            DisplayName = displayName ?? $"GPO Backup {dirGuid}",
            BackupPath = backupDir
        };
    }

    private static DomainGpoBackupInfo ParseBkupInfoXml(string xmlPath, string backupDir, string dirGuid)
    {
        var settings = new XmlReaderSettings
        {
            DtdProcessing = DtdProcessing.Prohibit,
            XmlResolver = null,
            IgnoreWhitespace = true
        };

        string? displayName = null;
        string? gpoGuid = null;

        using var reader = XmlReader.Create(xmlPath, settings);
        while (reader.Read())
        {
            if (reader.NodeType != XmlNodeType.Element)
                continue;

            switch (reader.LocalName)
            {
                case "GPODisplayName":
                    displayName = reader.ReadElementContentAsString()?.Trim();
                    break;
                case "GPOGuid":
                    gpoGuid = reader.ReadElementContentAsString()?.Trim();
                    break;
            }
        }

        return new DomainGpoBackupInfo
        {
            BackupId = dirGuid,
            GpoGuid = gpoGuid,
            DisplayName = displayName ?? $"GPO Backup {dirGuid}",
            BackupPath = backupDir
        };
    }

    private static ControlRecord CreateControlRecord(DomainGpoBackupInfo backup, string packName)
    {
        return new ControlRecord
        {
            ControlId = Guid.NewGuid().ToString("n"),
            ExternalIds = new ExternalIds
            {
                RuleId = $"DomainGPO_{backup.BackupId}",
                BenchmarkId = "domain-gpo-backup"
            },
            Title = $"Domain GPO: {backup.DisplayName}",
            Severity = "medium",
            Discussion = $"Domain-level GPO backup for GPMC import. Backup ID: {backup.BackupId}" +
                (string.IsNullOrWhiteSpace(backup.GpoGuid) ? string.Empty : $", GPO GUID: {backup.GpoGuid}"),
            CheckText = $"Verify domain GPO '{backup.DisplayName}' is imported and linked to the appropriate OU.",
            FixText = $"Import GPO backup '{backup.BackupId}' via GPMC or Import-GPO cmdlet on a domain controller.",
            IsManual = true,
            Applicability = new Applicability
            {
                OsTarget = OsTarget.Unknown,
                RoleTags = new[] { RoleTemplate.DomainController },
                ClassificationScope = ScopeTag.Unknown,
                Confidence = Confidence.High
            },
            Revision = new RevisionInfo
            {
                PackName = packName
            }
        };
    }

    private static string? FindGposRoot(string extractedRoot)
    {
        // Direct GPOs/ folder
        var direct = Path.Combine(extractedRoot, "GPOs");
        if (Directory.Exists(direct))
            return direct;

        // Case-insensitive search
        try
        {
            return Directory.EnumerateDirectories(extractedRoot, "GPOs", SearchOption.TopDirectoryOnly)
                .FirstOrDefault()
                ?? Directory.EnumerateDirectories(extractedRoot, "*", SearchOption.TopDirectoryOnly)
                    .FirstOrDefault(d => string.Equals(Path.GetFileName(d), "GPOs", StringComparison.OrdinalIgnoreCase));
        }
        catch
        {
            return null;
        }
    }

    private static bool IsGuidLike(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return false;

        var trimmed = name.Trim('{', '}', ' ');
        return Guid.TryParse(trimmed, out _);
    }
}

public sealed class DomainGpoBackupInfo
{
    public string BackupId { get; set; } = string.Empty;
    public string? GpoGuid { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public string BackupPath { get; set; } = string.Empty;
}

public sealed class DomainGpoParseResult
{
    public IReadOnlyList<ControlRecord> Controls { get; set; } = Array.Empty<ControlRecord>();
    public IReadOnlyList<DomainGpoBackupInfo> Backups { get; set; } = Array.Empty<DomainGpoBackupInfo>();
    public List<string> Warnings { get; set; } = new();
}
