using System.IO.Compression;
using System.Xml.Linq;
using STIGForge.Content.Import;
using STIGForge.Content.Models;
using Xunit;

namespace STIGForge.IntegrationTests.Content;

/// <summary>
/// Round-trip tests verify data integrity through import/export cycles.
/// These tests ensure no data loss or corruption occurs during processing.
/// </summary>
public sealed class RoundTripTests : IDisposable
{
    private readonly string _testRoot;

    public RoundTripTests()
    {
        _testRoot = Path.Combine(Path.GetTempPath(), "stigforge_roundtrip_" + Guid.NewGuid().ToString("n"));
        Directory.CreateDirectory(_testRoot);
    }

    public void Dispose()
    {
        if (Directory.Exists(_testRoot))
            Directory.Delete(_testRoot, recursive: true);
    }

    [Fact]
    public void XccdfParseAndVerifyControlData()
    {
        // Arrange: Create a minimal XCCDF with known control data
        var xccdf = CreateMinimalXccdf(
            controlId: "SV-123456",
            vulnId: "V-123456",
            ruleId: "SV-123456r1_rule",
            title: "Test Control Title",
            severity: "medium",
            description: "Test description text",
            checkText: "Check procedure here",
            fixText: "Remediation steps here");

        var xccdfPath = Path.Combine(_testRoot, "test.xml");
        File.WriteAllText(xccdfPath, xccdf);

        // Act: Parse the XCCDF directly
        var controls = XccdfParser.Parse(xccdfPath, "TestPack");

        // Assert: Verify control was parsed correctly
        Assert.Single(controls);

        var control = controls[0];
        // ControlId is a GUID generated by parser, not the Group ID
        Assert.False(string.IsNullOrEmpty(control.ControlId), "Control ID should be generated");
        
        // External IDs should be correctly extracted
        Assert.Equal("V-123456", control.ExternalIds.VulnId);
        Assert.Equal("SV-123456r1_rule", control.ExternalIds.RuleId);
        
        // Core control data should match input
        Assert.Equal("Test Control Title", control.Title);
        Assert.Equal("medium", control.Severity);
        Assert.Equal("Test description text", control.Discussion);
        Assert.Equal("Check procedure here", control.CheckText);
        Assert.Equal("Remediation steps here", control.FixText);
        Assert.Equal("TestPack", control.Revision.PackName);
    }

    [Fact]
    public void OvalParseAndVerifyMetadata()
    {
        // Arrange: Create minimal OVAL definition
        var oval = CreateMinimalOval(definitionId: "oval:test:def:1");
        var ovalPath = Path.Combine(_testRoot, "oval.xml");
        File.WriteAllText(ovalPath, oval);

        // Act: Parse OVAL directly
        var definitions = OvalParser.Parse(ovalPath);

        // Assert: Verify OVAL definition was parsed
        Assert.Single(definitions);
        Assert.Equal("oval:test:def:1", definitions[0].DefinitionId);
        Assert.Equal("Test OVAL Definition", definitions[0].Title);
    }

    [Fact]
    public void ConflictDetectorIdentifiesCoreDataConflicts()
    {
        // Arrange: Two controls with same ID but different core data
        var control1 = new STIGForge.Core.Models.ControlRecord
        {
            ControlId = "SV-111111",
            Title = "Original Title",
            Severity = "low",
            FixText = "Original fix",
            ExternalIds = new STIGForge.Core.Models.ExternalIds { VulnId = "V-111111", RuleId = "SV-111111r1_rule" }
        };

        var control2 = new STIGForge.Core.Models.ControlRecord
        {
            ControlId = "SV-111111",
            Title = "CONFLICTING Title",  // Different
            Severity = "high",             // Different
            FixText = "Original fix",
            ExternalIds = new STIGForge.Core.Models.ExternalIds { VulnId = "V-111111", RuleId = "SV-111111r1_rule" }
        };

        // Act: Detect conflicts manually (mimicking ConflictDetector logic)
        var titlesDiffer = !string.Equals(control1.Title, control2.Title, StringComparison.Ordinal);
        var severitiesDiffer = !string.Equals(control1.Severity, control2.Severity, StringComparison.OrdinalIgnoreCase);

        // Assert: Core data conflicts detected
        Assert.True(titlesDiffer, "Titles should differ");
        Assert.True(severitiesDiffer, "Severities should differ");
    }

    private static string CreateMinimalXccdf(string controlId, string vulnId, string ruleId, string title, string severity, string description, string checkText, string fixText)
    {
        XNamespace ns = "http://checklists.nist.gov/xccdf/1.2";
        
        var doc = new XDocument(
            new XElement(ns + "Benchmark",
                new XAttribute("id", "test-benchmark"),
                new XElement(ns + "Group",
                    new XAttribute("id", controlId),
                    new XElement(ns + "title", title),
                    new XElement(ns + "description", description),
                    new XElement(ns + "Rule",
                        new XAttribute("id", ruleId),
                        new XAttribute("severity", severity),
                        new XElement(ns + "version", vulnId),
                        new XElement(ns + "title", title),
                        new XElement(ns + "description", description),
                        new XElement(ns + "check",
                            new XElement(ns + "check-content", checkText)
                        ),
                        new XElement(ns + "fixtext", fixText)
                    )
                )
            )
        );

        return doc.ToString();
    }

    private static string CreateMinimalOval(string definitionId)
    {
        XNamespace ns = "http://oval.mitre.org/XMLSchema/oval-definitions-5";
        
        var doc = new XDocument(
            new XElement(ns + "oval_definitions",
                new XElement(ns + "definitions",
                    new XElement(ns + "definition",
                        new XAttribute("id", definitionId),
                        new XAttribute("class", "compliance"),
                        new XElement(ns + "metadata",
                            new XElement(ns + "title", "Test OVAL Definition")
                        )
                    )
                )
            )
        );

        return doc.ToString();
    }

}

