using System.Text;
using Microsoft.Extensions.Logging;

namespace STIGForge.Apply.Snapshot;

public sealed class RollbackScriptGenerator
{
    private readonly ILogger<RollbackScriptGenerator> _logger;

    public RollbackScriptGenerator(ILogger<RollbackScriptGenerator> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public string GenerateScript(SnapshotResult snapshot)
    {
        if (snapshot == null)
            throw new ArgumentNullException(nameof(snapshot));

        if (string.IsNullOrWhiteSpace(snapshot.SnapshotId))
            throw new ArgumentException("SnapshotId cannot be empty.", nameof(snapshot));

        if (string.IsNullOrWhiteSpace(snapshot.SecurityPolicyPath))
            throw new ArgumentException("SecurityPolicyPath cannot be empty.", nameof(snapshot));

        if (string.IsNullOrWhiteSpace(snapshot.AuditPolicyPath))
            throw new ArgumentException("AuditPolicyPath cannot be empty.", nameof(snapshot));

        if (!File.Exists(snapshot.SecurityPolicyPath))
            throw new FileNotFoundException("Security policy file not found.", snapshot.SecurityPolicyPath);

        if (!File.Exists(snapshot.AuditPolicyPath))
            throw new FileNotFoundException("Audit policy file not found.", snapshot.AuditPolicyPath);

        var scriptPath = Path.Combine(
            Path.GetDirectoryName(snapshot.SecurityPolicyPath) ?? string.Empty,
            $"rollback_{snapshot.SnapshotId}.ps1");

        var script = GenerateScriptContent(snapshot);
        File.WriteAllText(scriptPath, script, Encoding.UTF8);

        _logger.LogInformation("Rollback script generated: {Path}", scriptPath);
        return scriptPath;
    }

    private string GenerateScriptContent(SnapshotResult snapshot)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Rollback script generated by STIGForge");
        sb.AppendLine($"# Snapshot ID: {snapshot.SnapshotId}");
        sb.AppendLine($"# Created: {snapshot.CreatedAt:O}");
        sb.AppendLine($"# Recovery artifact: {snapshot.SecurityPolicyPath}");
        sb.AppendLine($"# Recovery artifact: {snapshot.AuditPolicyPath}");
        sb.AppendLine("# Rollback is operator-initiated. Review artifacts before execution.");
        sb.AppendLine();
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();

        // Restore security policy
        var qSecPol = EscapePowerShellSingleQuoted(snapshot.SecurityPolicyPath);
        sb.AppendLine("Write-Host 'Restoring security policy...'");
        sb.AppendLine($"secedit /configure /cfg '{qSecPol}' /db secedit.sdb /overwrite /quiet");
        sb.AppendLine();

        // Restore audit policy
        var qAuditPol = EscapePowerShellSingleQuoted(snapshot.AuditPolicyPath);
        sb.AppendLine("Write-Host 'Restoring audit policy...'");
        sb.AppendLine($"auditpol /restore /file:'{qAuditPol}'");
        sb.AppendLine();

        // Restore LGPO state (optional)
        if (!string.IsNullOrWhiteSpace(snapshot.LgpoStatePath) && File.Exists(snapshot.LgpoStatePath))
        {
            var qLgpo = EscapePowerShellSingleQuoted(snapshot.LgpoStatePath);
            sb.AppendLine("if (Test-Path '" + qLgpo + "') {");
            sb.AppendLine("    Write-Host 'Restoring LGPO state...'");
            sb.AppendLine($"    & 'LGPO.exe' /restore '{qLgpo}'");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("Write-Host 'Rollback complete. Reboot recommended.'");

        return sb.ToString();
    }

    /// <summary>Escapes a value for use inside a PowerShell single-quoted string. Only single-quote needs escaping.</summary>
    private static string EscapePowerShellSingleQuoted(string value) => value.Replace("'", "''");

    /// <summary>
    /// Escapes a value for use inside a PowerShell double-quoted string.
    /// Escapes: backtick, dollar sign, double-quote, and backslash before expandable characters.
    /// </summary>
    private static string EscapePowerShellDoubleQuoted(string value)
        => value
            .Replace("`", "``")
            .Replace("$", "`$")
            .Replace("\"", "`\"");
}
